### ISSUE TITLE
Exception when displaying the data from a table

### ISSUE THREAD

**Issue by adrianboangiu** [PhilippSalvisberg/plsql-formatter-settings#1]
Hello,

After patching dbtools-common.jar as explained I cannot display the data from the tables. I have an exception as shown in the attached images.
![image](https://github.com/user-attachments/assets/fb13cf7c-7e00-4a75-8037-c81bf34cf01d)
![image](https://github.com/user-attachments/assets/5e894f39-247e-422b-aba9-ca44bb0bf1f2)

If I switch to the original dbtools-common.jar and the problem disappear.
The version of my SQL Developer is the good one 23.1.1.345 and the version of SQLcl used for the patch was 23.4.0.023.2321.

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this issue. In this case, I recommend keeping the original `dbtools-comman.jar`. A new SQLDev should be released "soon".  Then I will update the grammar and remove all patching instructions. They have some unwanted side effects.
